name: tedious_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  path: ^1.8.0
  # eventify: ^1.0.1
  buffer:
  logger:
  # charset_converter:
  # node_interop:
    # path: ./node_interop-2.1.0
  sprintf:
  crypto:
  convert:
  pointycastle:
  dcache:
  # js:
  # ts_definition:
  events_emitter:
  # magic_buffer: ^0.0.15
  bloc:
  chalkdart: ^2.0.9
  equatable:
  magic_buffer_copy:
    path: c:/users/kareemzaher/desktop/darTedious/magic_buffer_copy
  buffer_list:
    path: c:/users/kareemzaher/desktop/darTedious/buffer_list
  rxdart:  
  dartz:
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
